In [1]:
import os
import numpy as np
# import working directory to check functions
os.chdir('/Users/Dominik/R-workspace/cecelia/inst')

# config
import py.config_utils as cfg

%load_ext autoreload
%autoreload 2

In [35]:
a = np.array([[0,5,2,3,2,3,4],[0,5,2,3,2,3,4]], dtype = np.uint32)
b = np.array([[0,5,4,7,4,7,6],[0,5,2,3,2,3,4]], dtype = np.uint32)

In [38]:
_, idx_a =  np.unique(a, return_index=True)

In [39]:
_, idx_b =  np.unique(b, return_index=True)

In [43]:
zip(a.ravel()[sorted(idx_a)], b.ravel()[sorted(idx_b)])

In [32]:
a[a == 4] = 5

In [33]:
a

array([0, 5, 2, 3, 2, 3, 5], dtype=uint32)

In [26]:
for x, y in zip(a[sorted(idx_a)], b[sorted(idx_b)]):
    print(x, y)

0 0
5 5
2 4
3 7
4 6


In [7]:
from scipy.sparse import coo_array, csc_array, csr_array

In [5]:
x = np.array([0, 0, 1, 0])
y = np.array([0, 0, 1, 2])

In [8]:
z = [1] * len(x)

overlap = coo_array((z, (x, y)), shape = (len(x), len(y)), dtype = np.uint16)
overlap_array = overlap.toarray()

In [65]:
overlap.argmax(axis=1)[:,0]

matrix([[0],
        [1],
        [0],
        [0]])

In [71]:
from sklearn import preprocessing
iou = preprocessing.normalize(overlap, norm='l1', axis=1)

In [72]:
iou[iou < 0.4] = 0

In [73]:
x=np.array(iou.argmax(axis = 0))[0,:]
y=np.arange(0,x.size,1)
z=iou.max(axis=0).toarray()[0,:]

iou = coo_array((z, (x, y)), shape = (len(x), len(y)))

In [115]:
a = np.array([1,2,3,4,5])
x = [2,3]

In [121]:
a[np.isin(a, [])] = 0

In [122]:
a

array([1, 0, 0, 4, 5])

In [76]:
ino = np.nonzero(iou.max(axis = 1).toarray() == 0.0)[0]

In [102]:
iou.toarray().argmax(axis=1)

array([0, 1, 0, 0])

In [113]:
 iou.argmax(axis = 1).A.ravel()

array([0, 1, 0, 0])

In [100]:
istitch.reshape((1,4)).shape

(1, 4)

In [165]:
n_pixels_x = np.sum(overlap_array, axis = 0, keepdims = True)
n_pixels_true = np.sum(overlap_array, axis = 1, keepdims = True)
(n_pixels_x + n_pixels_true)

array([[5, 4, 4, 3],
       [3, 2, 2, 1],
       [2, 1, 1, 0],
       [2, 1, 1, 0]], dtype=uint64)

In [196]:
n_pixels_x.dtype

dtype('uint64')

In [195]:
(n_pixels_x + n_pixels_true - overlap)

array([[3, 4, 3, 3],
       [3, 1, 2, 1],
       [2, 1, 1, 0],
       [2, 1, 1, 0]], dtype=uint64)

In [ ]:
n_pixels_x = np.sum(overlap_array, axis = 0, keepdims = True, dtype = np.uint16)
n_pixels_true = np.sum(overlap_array, axis = 1, keepdims = True, dtype = np.uint16)
n_compose = (n_pixels_x + n_pixels_true - overlap)
iou = np.divide(overlap_array, n_compose, dtype = np.float16, where = n_compose != 0)
iou.dtype
#iou[np.isnan(iou)] = 0.0

In [ ]:
(n_pixels_x + n_pixels_true - overlap).dtype

In [ ]:
def method_a(overlap):
    n_pixels_x = np.sum(overlap, axis = 0, keepdims = True, dtype = np.uint16)
    n_pixels_true = np.sum(overlap, axis = 1, keepdims = True, dtype = np.uint16)
    iou = overlap / (n_pixels_x + n_pixels_true - overlap)
    print(iou.dtype)
    #iou[np.isnan(iou)] = 0.0
    
    return iou

method_a(overlap_array)

In [ ]:
n_pixels_true.shape

In [ ]:
n_pixels_x = overlap.sum(axis = 0)
n_pixels_true = overlap.sum(axis = 1)
# reshape
n_pixels_true = n_pixels_true.reshape((n_pixels_true.shape[0], 1))

In [ ]:
n_pixels_x + n_pixels_true

In [ ]:
iou = overlap / (n_pixels_x + n_pixels_true - overlap)

In [ ]:
def method_b(overlap):
    n_pixels_x = overlap.sum(axis = 0)
    n_pixels_true = overlap.sum(axis = 1)
    # reshape
    n_pixels_true = n_pixels_true.reshape((n_pixels_true.shape[0], 1))
    n_compose = (n_pixels_x + n_pixels_true - overlap)
    
    iou = np.divide(overlap.toarray(), n_compose,
                    dtype = np.float16, where = n_compose != 0)
    iou[np.isnan(iou)] = 0.0
    
    return iou

method_b(overlap)

In [ ]:
if np.any(x) is True:
    print('hello')

In [ ]:
np.min(x > 2)

In [ ]:
import sys

def sizeof_fmt(num, suffix='B'):
    ''' by Fred Cirera,  https://stackoverflow.com/a/1094933/1870254, modified'''
    for unit in ['','Ki','Mi','Gi','Ti','Pi','Ei','Zi']:
        if abs(num) < 1024.0:
            return "%3.1f %s%s" % (num, unit, suffix)
        num /= 1024.0
    return "%.1f %s%s" % (num, 'Yi', suffix)

In [ ]:
def print_mem_usage(context, num_vars = 10):
    for name, size in sorted(((name, sys.getsizeof(value)) for name, value in list(
                          context.items())), key= lambda x: -x[1])[:num_vars]:
        print("{:>30}: {:>8}".format(name, sizeof_fmt(size)))

In [ ]:
print_mem_usage(locals(), 10)

In [ ]:
base_dir = '/Volumes/Analysis_SSD/Dominik/cecelia/projects/4DZwIe/ANALYSIS/'
im_path = os.path.join(base_dir, '0', 'Fi2BUU', 'ccidImage.ome.zarr')
cyto_path = os.path.join(base_dir, '1', 'Fi2BUU', 'labels', 'default.zarr')

In [ ]:
import py.zarr_utils as zarr_utils
import py.ome_xml_utils as ome_xml_utils
from py.dim_utils import DimUtils
import py.correction_utils as correction_utils
import py.label_utils as label_utils

In [ ]:
cyto_labels, _ = zarr_utils.open_labels_as_zarr(cyto_path)

In [ ]:
slices = (None, None, )
cyto_labels[0][]

In [ ]:
x = '/Volumes/Analysis_SSD/Dominik/TMP/x.zarr'

In [ ]:
zarr_shape = list(cyto_labels[0].shape)
zarr_chunks = list(zarr_utils.chunks(cyto_labels[0]))

In [ ]:
import zarr

In [ ]:
labels = zarr.open(
    x,
    mode = 'w',
    shape = tuple(zarr_shape),
    chunks = tuple(zarr_chunks),
    dtype = np.uint32)

In [ ]:
cur_slices_a = (slice(None), slice(0,21,1), slice(500,700,1), slice(400,600,1))
cur_slices_b = (slice(None), slice(0,21,1), slice(400,600,1), slice(400,600,1))
label_slices = tuple([0 if x == slice(None) else x for x in cur_slices_a])

In [ ]:
labels[label_slices] = np.amax(np.stack(
    label_utils.match_masks(
      # [alg_labels[j], labels[j][cur_slices]],
      [np.squeeze(cyto_labels[0][cur_slices_a]), np.squeeze(cyto_labels[0][cur_slices_b])],
      stitch_threshold = 0.2,
      remove_unmatched = False
      )
    ), axis = 0)

In [ ]:
nuc_array = zarr_utils.fortify(nuc_labels[0])
cyto_array = zarr_utils.fortify(cyto_labels[0])

In [ ]:
x = nuc_array
y = cyto_array

In [ ]:
# put label arrays into standard form then flatten them 
x = nuc_array.ravel()
y = cyto_array.ravel()

# preallocate a 'contact map' matrix
overlap = np.zeros((1 + x.max(), 1 + y.max()), dtype = np.uint)

# loop over the labels in x and add to the corresponding
# overlap entry. If label A in x and label B in y share P
# pixels, then the resulting overlap is P
# len(x)=len(y), the number of pixels in the whole image 
for i in range(len(x)):
    overlap[x[i], y[i]] += 1

In [ ]:
n_pixels_pred = np.sum(overlap, axis=0, keepdims=True)
n_pixels_true = np.sum(overlap, axis=1, keepdims=True)
iou = overlap / (n_pixels_pred + n_pixels_true - overlap)
iou[np.isnan(iou)] = 0.0

In [ ]:
(nuc_array * np.isin(nuc_array, [3])).unique()

In [ ]:
masks = {
    'nuc': nuc_array
    'cyto': cyto_array
}
stitch_threshold = 0.2

In [ ]:
[x.max() for x in masks if x is not None and x.max() > 0]

In [ ]:
mmax = masks[0].max()
empty = 0

for i in range(len(masks)-1):
    iou = intersection_over_union(masks[i+1], masks[i])[1:,1:]
    if not iou.size and empty == 0:
        masks[i+1] = masks[i+1]
        mmax = masks[i+1].max()
    elif not iou.size and not empty == 0:
        icount = masks[i+1].max()
        istitch = np.arange(mmax+1, mmax + icount+1, 1, int)
        mmax += icount
        istitch = np.append(np.array(0), istitch)
        masks[i+1] = istitch[masks[i+1]]
    else:
        iou[iou < stitch_threshold] = 0.0
        iou[iou < iou.max(axis=0)] = 0.0
        istitch = iou.argmax(axis=1) + 1
        ino = np.nonzero(iou.max(axis=1)==0.0)[0]
        istitch[ino] = np.arange(mmax+1, mmax+len(ino)+1, 1, int)
        mmax += len(ino)
        istitch = np.append(np.array(0), istitch)
        masks[i+1] = istitch[masks[i+1]]
        empty = 1

In [ ]:
import napari

viewer = napari.Viewer()

In [ ]:
viewer.add_labels(masks[0])
viewer.add_labels(masks[1])

In [ ]:
viewer.add_labels(masks[0])

In [ ]:
# show alignment
reg_im = zarr_utils.open_as_zarr('/Volumes/Analysis_SSD/Dominik/TMP/reg000.zarr')

colors = ['gray', 'magenta', 'cyan', 'yellow']
#for i, x in enumerate([3, 10, 17, 24]):
for i, x in enumerate([3, 10]):
    viewer.add_image(reg_im[0][0][0, x, :, :, :], colormap=colors[i], blending='additive')

In [ ]:
# get image information
im_zarrs = [zarr_utils.open_as_zarr(x, as_dask = True) for x in im_paths]
im_zarrs = [x[0] for x in im_zarrs]

In [ ]:
# create dim utils for images
dim_utils = [
    DimUtils(ome_xml_utils.parse_meta(x), use_channel_axis = True) for x in im_paths
]

for i, x in enumerate(dim_utils):
    x.calc_image_dimensions(im_zarrs[i][0].shape)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import math
import shutil
import zarr

from skimage.color import separate_stains, combine_stains, hdx_from_rgb, rgb_from_hdx
from skimage.registration import phase_cross_correlation
from skimage.transform import warp_polar, rotate, rescale, warp, SimilarityTransform, AffineTransform
from skimage.util import img_as_float

In [ ]:
"""
Get shifts for image registration
"""
def image_registration_shifts(ims, channel_ids, radius = 1000, upsample_factor = 20):
    # warp image for rotation
    im_polar = warp_polar(np.amax(ims[0], axis = 0), radius = radius, scaling = 'log')
    
    shifts = list()
    rotations = list()
    
    # go through images and find shifts based on first image
    for i in range(1, len(ims)):
        # apply translation shifts
        shift, error, diffphase = phase_cross_correlation(ims[0], ims[i], upsample_factor = upsample_factor)
        shifts.append(shift)
        
        tform = SimilarityTransform(translation = (-shift[0], -shift[1]))
        im_warped = warp(ims[i], tform)

        # apply rotation
        other_polar = warp_polar(np.amax(im_warped, axis = 0), radius = radius, scaling = 'log')

        shift, error, diffphase = phase_cross_correlation(im_polar, other_polar, upsample_factor = upsample_factor)
        rotations.append(shift)

        tform = AffineTransform(rotation = math.radians(-shift[0]))
        im_warped = warp(im_warped, tform)

        # apply translation shifts
        shift, error, diffphase = phase_cross_correlation(ims[0], im_warped, upsample_factor = upsample_factor)
        shifts[-1] = shifts[-1] + shift
    
    # convert to array
    return np.vstack(shifts), np.vstack(rotations)

In [ ]:
"""
Register image
"""
def im_registration(
    input_arrays, dim_utils_list, phase_shift_channels,
    reg_path = None, normalise_percentile = 98,
    upsample_factor = 100, shifts = None):
    

In [ ]:
input_arrays = im_zarrs
dim_utils_list = dim_utils
phase_shift_channels = channel_ids
reg_path = '/Volumes/Analysis_SSD/Dominik/TMP/reg000'
shifts = None
upsample_factor = 20
normalise_percentile = 98

In [ ]:
# get shifts
if shifts is None:
    print('>> Get shifts')
    # get shifts from lowest res
    low_res = len(input_arrays[0]) - 1

    im_slices = [0 for _ in range(len(input_arrays[0][0].shape))]
    im_slices[dim_utils_list[0].dim_idx('X')] = slice(0, min([x.dim_val('X', scale = low_res) for x in dim_utils_list]))
    im_slices[dim_utils_list[0].dim_idx('Y')] = slice(0, min([x.dim_val('Y', scale = low_res) for x in dim_utils_list]))

    if dim_utils_list[0].is_3D() is True:
        im_slices[dim_utils_list[0].dim_idx('Z')] = slice(None)

    # get low resolution images for registration
    ims = list()

    for i, x in enumerate(input_arrays):
        im_slices[dim_utils[i].dim_idx('C')] = phase_shift_channels[i]
        ims.append(zarr_utils.fortify(x[low_res][tuple(im_slices)]))

        # normalise image
        percentile = (np.percentile(ims[-1], normalise_percentile),
                      np.percentile(ims[-1], 100 - normalise_percentile))
        ims[-1] = ((ims[-1] - percentile[1]) / (percentile[0] - percentile[1]))

    # get shifts and rotations
    shifts, rotations = image_registration_shifts(
        ims, phase_shift_channels,
        upsample_factor = upsample_factor)

In [ ]:
# get shifts summary
shifts_summary = correction_utils.shifts_summary(shifts, cumulative = False)

# get new image dimensions
reg_im_shape, reg_im_shape_round = correction_utils.correction_im_shape(
    input_arrays[0][0], dim_utils_list[0], shifts_summary
)

# get first image position
first_im_pos = correction_utils.correction_first_im_pos(
    reg_im_shape, dim_utils_list[0], shifts_summary
)

In [ ]:
first_im_pos

In [ ]:
# remove previous folder
if reg_path is not None and os.path.exists(reg_path) is True:
    shutil.rmtree(reg_path)

# add channels for new image
reg_im_shape_round = list(reg_im_shape_round)
# remove channel for registration from sum?
#reg_im_shape_round[dim_utils_list[0].dim_idx('C')] = sum([x.dim_val('C') - 1 for x in dim_utils_list]) + 1
reg_im_shape_round[dim_utils_list[0].dim_idx('C')] = sum([x.dim_val('C') for x in dim_utils_list])
reg_im_shape_round = tuple(reg_im_shape_round)

# create array
reg_zarr = zarr.create(
    reg_im_shape_round,
    dtype = input_arrays[0][0].dtype,
    chunks = input_arrays[0][0].chunksize,
    store = reg_path
)

# use first position for slice
slices = first_im_pos

In [ ]:
print('>> Apply shifts')

# go through images and register to first image
for i, x in enumerate(input_arrays):
    # create slice
    if i > 0:
        new_slices = list()

        # adjust slices
        for j, y in enumerate(slices):
            new_slices.append(slice(
              # subtract '1' because there is no
              # shift for the first frame
              y.start + shifts[i - 1, j],
              y.stop + shifts[i - 1, j],
              1
            ))

        # push back
        slices = new_slices

    # round for slicing
    new_slices = [slice(None) for _ in range(len(reg_im_shape_round))]

    # set Z, X, Y for new slices
    for j, y in enumerate(('Z', 'Y', 'X')):
        new_slices[dim_utils_list[i].dim_idx(y)] =  slice(round(slices[j].start), round(slices[j].stop), 1)

    # set channel for new slice
    prev_channels = sum([x.dim_val('C') for x in dim_utils_list[0:i]])
    new_slices[dim_utils_list[i].dim_idx('C')] = slice(
        prev_channels, prev_channels + dim_utils_list[i].dim_val('C'), 1)

    # convert to tuple
    new_slices = tuple(new_slices)
    
    print(f'>> reg {i}')
    print(f'> {new_slices}')

    # add to image list
    new_image = np.zeros(reg_im_shape_round)

    # check that slices match dimension
    if new_image[new_slices].shape != x[0].shape:
        # get wrong dimensions
        dif_dim = [x - y for x, y in zip(
            new_image[new_slices].shape,
            x[0].shape
        )]

        # adjust dimensions
        new_slices = list(new_slices)

        for j, y in enumerate(dif_dim):
            if y > 0:
              # add?
              new_slices[j] = slice(
                  new_slices[j].start + y,
                  new_slices[j].stop, 1)

            if y < 0:
              # add?
              if new_slices[j].start - y >= 0:
                new_slices[j] = slice(
                  new_slices[j].start + y,
                  new_slices[j].stop, 1)

              # subtract?
              elif new_slices[j].stop + y < reg_zarr.shape[j]:
                new_slices[j] = slice(
                  new_slices[j].start,
                  new_slices[j].stop + y, 1)

        new_slices = tuple(new_slices)

    # apply rotation and push to zarr
    reg_zarr[new_slices] = warp(x[0], AffineTransform(rotation = math.radians(-rotations[i - 1][0])))

In [ ]:
im_registration(im_zarrs, dim_utils, channel_ids, reg_path)

In [ ]:
# prepare image to compare
before_rgb_im = combine_stains(np.dstack([np.amax(x, axis = 0) for x in ims]), rgb_from_hdx)

In [ ]:
# merge signal
after_rgb_im = combine_stains(np.dstack(np.amax(x, axis = 0) for x in warped_im), rgb_from_hdx)
after_rgb_zoom = combine_stains(np.dstack(np.amax(x, axis = 0) for x in warped_zarr), rgb_from_hdx)

fig, axes = plt.subplots(2, 2, figsize=(40, 40))
ax = axes.ravel()
ax[0].set_title("Nuclei")

show_slices[dim_utils[0].dim_idx('C')] = channel_ids[0]
ax[0].set_title("Before")
ax[0].imshow(before_rgb_im)
ax[1].set_title("Aligned")
ax[1].imshow(after_rgb_im)
ax[2].set_title("Before")
ax[2].imshow(before_rgb_zoom)
ax[3].set_title("Aligned")
ax[3].imshow(after_rgb_zoom)
plt.show()